# Generated by Django 4.1.6 on 2023-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_explorer', '0003_alter_csvfiles_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiles',
            name='file_owner',
            field=models.CharField(default='auth.User', max_length=255),
        ),
    ]
