# Generated by Django 4.1.6 on 2023-02-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_explorer', '0004_csvfiles_file_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfiles',
            name='file_owner',
        ),
        migrations.AddField(
            model_name='csvfiles',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
